config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get 'tasks', to: 'tasks#index'
  # get 'tasks/new', to: 'tasks#new'
  # get 'tasks/:id', to: 'tasks#show', as: :task
  # post 'tasks', to: 'tasks#create'
  # get 'tasks/:id/edit', to: 'tasks#edit'
  # patch 'tasks/:id', to: 'tasks#update'
  resources :tasks
  delete 'tasks/:id', to: 'tasks#destroy', as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    validates :title, presence: true
    validates :details, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
before_action :find_task, only: [:show, :edit, :update, :destroy]
    def index
        @tasks = Task.all
    end

    def new
        @task = Task.new
    end

    def create
        @task = Task.new(params_task)
        @task.save
        redirect_to tasks_path
    end

    def show
    end

    def edit
    end

    def update
        @task.update(params_task)
        redirect_to tasks_path
    end

    def destroy
        @task.destroy
        redirect_to tasks_path
    end

    private

    def find_task
        @task = Task.find(params[:id])
    end

    def params_task
        params.require(:task).permit(:title, :details, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1 class="display-3 m-3">Edit Task</h1>

<div class="form-group m-5">
<%= form_for(@task) do |f| %>
  <%= f.label :Title, class:"font-italic display-4" %>
  <br>
  <%= f.text_field :title, class:"form-control"%>
  <br><br>
  <%= f.label :Details, class:"font-italic display-4"%>
  <br>
  <%= f.text_field :details, class:"form-control" %>
  <br><br>
  <%= f.label :Status, class:"font-italic display-4"%>
  &nbsp;&nbsp;
  <%= f.check_box :completed%>
  <br><br>
  <%= f.submit "Update Task", class:"btn btn-success m-2 p-3"%>
  <%= link_to "Back", tasks_path, class:"btn btn-warning m-2 p-3" %>
<% end %>
</div>

app/views/tasks/index.html.erb
<h1 class="display-3 m-3">My tasks</h1>

<ul class="list-group ">
<% @tasks.each do |task| %>
<li><%= link_to task.title, task_path(task), class:"list-group-item m-3 p-2 font-italic display-4" %> 
</li>
<% end %>
</ul>

<%= link_to "Add a new Task", new_task_path, class: "btn btn-primary m-4 p-3" %>

app/views/tasks/new.html.erb
<h1>Form Task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1 class="display-3 m-3"><%= @task.title %></h1>

<p class="font-italic m-5 display-4"><%= @task.details %> </p>

<div class="font-italic m-5 display-4"> 
    <% if @task.completed %>
    Status: Completed Successfully.✅
    <% else %>
    Status: This Task has not been completed yet.🟩
    <% end %>
</div>

<%= link_to "Edit the Task", edit_task_path, class:"btn btn-secondary m-2 p-3" %> 


<%= link_to "Delete", destroy_path, method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-danger m-2 p-3" %>


<%= link_to "Back", tasks_path, class:"btn btn-warning m-2 p-3" %>